services:
  fastapi_app:
    build:
      context: . # Caminho onde est치 o Dockerfile (raiz do projeto)
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Mapeia a porta local 8000 para a porta 8000 do container
    env_file:
      - .env # Carrega vari치veis de ambiente do arquivo .env
    volumes:
      - ./src:/app/src # Mapeia o diret칩rio src local para o diret칩rio src no container
